# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  soap-app:
    image: soap
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://soap-postgresql:5432/soap
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://soap-postgresql:5432/soap
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  soap-postgresql:
    image: postgres:14.4
    # volumes:
    #   - ~/volumes/jhipster/soap/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=soap
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
